// ========== Firebase Configuration ==========
// Generated by BLU3Y Glass System

const firebaseConfig = {
    apiKey: "AIzaSyDBguT0T_TR0IVRCqjd-5_yGO3MEGrV7FI",
    authDomain: "gomlf-c26ce.firebaseapp.com",
    databaseURL: "https://gomlf-c26ce-default-rtdb.firebaseio.com",
    projectId: "gomlf-c26ce",
    storageBucket: "gomlf-c26ce.firebasestorage.app",
    messagingSenderId: "18853650392",
    appId: "1:18853650392:web:80bf57c23a28158671dcad",
    measurementId: "G-8XNVS6EYPE"
};

// Initialize Firebase
firebase.initializeApp(firebaseConfig);
const auth = firebase.auth();
const db = firebase.database();
const storage = firebase.storage();

// Cloudinary Configuration
const CLOUD_NAME = "dmla61v7n";
const UPLOAD_PRESET = "so2_mk";
const CLOUDINARY_COLLECTION_URL = "https://collection.cloudinary.com/dmla61v7n";

console.log('💙 BLU3Y Glass Firebase + Cloudinary Ready');
